### ISSUE TITLE
Add 'onSuccess' callback 

### ISSUE THREAD

**Issue by jesusrp98** [ja2375/add_2_calendar#20]
Add a new parameter to the `Add2Calendar.addEvent2Cal` method, called `onSuccess`, which would be called once an specific event has been successfully added to the calendar.

The implementation of a similar method, called `onFailure`, would be cool. This other method would be called of something wrong happens while trying to add a new event.

**Comment by ja2375** [comment]
Hello,

Sorry for the delay.

We can add those callbacks. But it is already possible to perform actions on success and on failure.
The addEvent2Cal(Event) returns a bool, which is true when the event was successfully creeated or false otherwise.

Knowing that, do you think it would be necessary to add these callbacks?

**Comment by jesusrp98** [comment]
I didn't know that behaviour of the `addEvent2Cal` methond, which returns a futrure boolean. This will do the trick.

Thank you very much!!

**Comment by ja2375** [comment]
You are welcome :)
