### ISSUE TITLE
Set endDate  as not required

### ISSUE THREAD

**Issue by TJMusiitwa** [ja2375/add_2_calendar#39]
Hey I am working on app that has scheduled events that I am parsing from Firestore and are for the most part one day events.  It would benefit greatly if you could set the endDate as not required to better accommodate for such event scenarios. The startDate should remain required of course.

**Comment by diegogarciar** [comment]
Hello, I tried to develop the feature but endDate is always required by the os (at least iOS). For all day events you still need to set the end date. This si because you can either have multi all-day events or single one day events. Some examples

```
birthday:
final startDate: DateTime(2020, 1, 1, 9),

Event(
startDate: startDate,
endDate: startDate
)// one day all day event


convention:
Event(
startDate: DateTime(2020, 1, 1, 9),
endDate: DateTime(2020, 1, 1, 11),
) //two day all day event

```

So in your case, just set the endDate same as start date for one day all day event.
